version: "3"

services:
  ##
  # Programming: Node.js (JavaScript)
  ##
  node:
    image: node:alpine # https://hub.docker.com/_/node
    container_name: tmp_node
    tty: true
    ports:
      - 3000:3000

  ##
  # Database: MongoDB
  ##
  mongo:
    image: mongo # https://hub.docker.com/_/mongo
    container_name: tmp_mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express # https://hub.docker.com/_/mongo-express
    container_name: tmp_mongo_express
    ports:
      - 8081:8081
