version: "3"

services:
  ##
  # Programming: Node.js (JavaScript)
  ##
  node:
    image: node:alpine # https://hub.docker.com/_/node
    container_name: tmp_node
    tty: true
    ports:
      - 3000:3000

  ##
  # Database: MongoDB
  ##
  mongo:
    image: mongo # https://hub.docker.com/_/mongo
    container_name: tmp_mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express # https://hub.docker.com/_/mongo-express
    container_name: tmp_mongo_express
    ports:
      - 8081:8081

  ##
  # Database: MySQL
  ##
  mysql:
    image: mysql # https://hub.docker.com/_/mysql
    container_name: tmp_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer # https://hub.docker.com/_/adminer
    container_name: tmp_adminer
    ports:
      - 8888:8080
    links:
      - mysql:db
